package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Buildconfig2'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Buildconfig2")
    name = "buildconfig2"

    triggers {
        schedule {
            schedulingPolicy = cron {
                seconds = "2"
                minutes = "1"
            }
            branchFilter = ""
            triggerBuild = always()
        }
    }
}))

